name: rifad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  flutter_verification_code: ^1.1.7
  icons_launcher: ^3.0.1
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  hijri: ^3.0.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/images/endOfPage.png
    - assets/images/recaptcha.png
    - assets/icons/Frame 1.png
    - .env


  fonts:
    - family: GE SS Two
      fonts:
        - asset: assets/fonts/GE SS Two/GE SS Two_MEDIUM_5.otf
          weight: 500
        - asset: assets/fonts/GE SS Two/GE SS Two_TEXT_LIGHT.otf
          weight: 200
        - asset: assets/fonts/GE SS Two/GE SS Two_Bold_4.otf
          weight: 700
    - family: FF Shamel Family
      fonts:
        - asset: assets/fonts/FFShamelFamily.ttf
 


icons_launcher:
  image_path: "assets/icons/Frame 1.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# dart run icons_launcher:create