name: rifad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  flutter_verification_code: ^1.1.7
  icons_launcher: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg/


  fonts:
    - family: GE SS Two
      fonts:
        - asset: assets/fonts/GE SS Two/GE SS Two_MEDIUM_5.otf
          weight: 500
        - asset: assets/fonts/GE SS Two/GE SS Two_TEXT_LIGHT.otf
          weight: 200
        - asset: assets/fonts/GE SS Two/GE SS Two_Bold_4.otf
          weight: 700
    # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# dart run icons_launcher:create